-- LabPrice — PostgreSQL 16 DDL
-- ----------------------------------------------------------------------------
-- Base CREATE TABLE statements are generated by `prisma migrate` from
-- schema.prisma. This file contains SQL that Prisma cannot model:
--   • Extensions (citext, pg_trgm, btree_gin)
--   • CITEXT email column
--   • GENERATED tsvector column + GIN full-text/trigram indexes
--   • RANGE partitioning of 4 high-volume time-series tables
--   • CHECK constraints and partial unique indexes
-- ----------------------------------------------------------------------------

-- ============================================================================
-- 0. EXTENSIONS
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS citext;      -- case-insensitive email
CREATE EXTENSION IF NOT EXISTS pg_trgm;     -- fuzzy/typo-tolerant search
CREATE EXTENSION IF NOT EXISTS btree_gin;   -- composite GIN indexes

-- ============================================================================
-- 1. CITEXT — case-insensitive email
-- ============================================================================

ALTER TABLE users ALTER COLUMN email TYPE CITEXT;

-- ============================================================================
-- 2. GENERATED COLUMN — tests.search_vector
-- ============================================================================
-- Prisma cannot model GENERATED columns. This must be applied after the base
-- table is created by prisma migrate.

ALTER TABLE tests ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(short_name, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(purpose, '')), 'C')
    ) STORED;

-- ============================================================================
-- 3. GIN INDEXES — full-text and fuzzy search
-- ============================================================================

CREATE INDEX tests_search_gin ON tests USING GIN (search_vector);
CREATE INDEX tests_name_trgm  ON tests USING GIN (name gin_trgm_ops);

-- ============================================================================
-- 4. RANGE-PARTITIONED TABLES
-- ============================================================================
-- Prisma cannot express PARTITION BY RANGE. These tables must be created
-- manually instead of via Prisma's generated CREATE TABLE. The Prisma model
-- still exists (for type generation and relations) but the actual DDL comes
-- from here.
--
-- PRIMARY KEY must include the partition key for partitioned tables.
-- FK constraints on partitioned tables are supported in PG 16.
-- ----------------------------------------------------------------------------

-- 4a. price_history — partitioned by observed_at ----------------------------

CREATE TABLE price_history (
    id            BIGSERIAL,
    offering_id   TEXT            NOT NULL,
    old_price     NUMERIC(10,2),
    new_price     NUMERIC(10,2)   NOT NULL,
    observed_at   TIMESTAMPTZ     NOT NULL,
    source        "PriceSource"   NOT NULL,
    scrape_run_id TEXT,
    created_at    TIMESTAMPTZ     NOT NULL DEFAULT now(),
    PRIMARY KEY (id, observed_at),
    CONSTRAINT fk_ph_offering FOREIGN KEY (offering_id)
        REFERENCES offerings(id) ON DELETE CASCADE,
    CONSTRAINT fk_ph_scrape_run FOREIGN KEY (scrape_run_id)
        REFERENCES scrape_runs(id) ON DELETE SET NULL
) PARTITION BY RANGE (observed_at);

CREATE INDEX price_history_offering_time_idx
    ON price_history (offering_id, observed_at DESC);
CREATE INDEX price_history_source_idx
    ON price_history (source);

-- Example monthly partitions:
CREATE TABLE price_history_2026_06 PARTITION OF price_history
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE price_history_2026_07 PARTITION OF price_history
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE price_history_2026_08 PARTITION OF price_history
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

-- 4b. affiliate_clicks — partitioned by clicked_at -------------------------

CREATE TABLE affiliate_clicks (
    id              BIGSERIAL,
    offering_id     TEXT            NOT NULL,
    user_id         TEXT,
    session_id      TEXT,
    ip_hash         TEXT,
    user_agent_hash TEXT,
    referrer        TEXT,
    clicked_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    PRIMARY KEY (id, clicked_at),
    CONSTRAINT fk_ac_offering FOREIGN KEY (offering_id)
        REFERENCES offerings(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ac_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE SET NULL
) PARTITION BY RANGE (clicked_at);

CREATE INDEX affiliate_clicks_clicked_idx
    ON affiliate_clicks (clicked_at);
CREATE INDEX affiliate_clicks_offering_time_idx
    ON affiliate_clicks (offering_id, clicked_at);
CREATE INDEX affiliate_clicks_user_idx
    ON affiliate_clicks (user_id) WHERE user_id IS NOT NULL;

-- Example monthly partitions:
CREATE TABLE affiliate_clicks_2026_06 PARTITION OF affiliate_clicks
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE affiliate_clicks_2026_07 PARTITION OF affiliate_clicks
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE affiliate_clicks_2026_08 PARTITION OF affiliate_clicks
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

-- 4c. search_logs — partitioned by created_at -------------------------------

CREATE TABLE search_logs (
    id              BIGSERIAL,
    query           TEXT            NOT NULL,
    results_count   INTEGER         NOT NULL,
    user_id         TEXT,
    session_id      TEXT,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    PRIMARY KEY (id, created_at),
    CONSTRAINT fk_sl_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE SET NULL
) PARTITION BY RANGE (created_at);

CREATE INDEX search_logs_created_idx
    ON search_logs (created_at);
CREATE INDEX search_logs_user_idx
    ON search_logs (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX search_logs_zero_results_idx
    ON search_logs (results_count) WHERE results_count = 0;

-- Example monthly partitions:
CREATE TABLE search_logs_2026_06 PARTITION OF search_logs
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE search_logs_2026_07 PARTITION OF search_logs
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE search_logs_2026_08 PARTITION OF search_logs
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

-- 4d. page_views — partitioned by created_at --------------------------------

CREATE TABLE page_views (
    id              BIGSERIAL,
    path            TEXT            NOT NULL,
    test_id         TEXT,
    user_id         TEXT,
    session_id      TEXT,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    PRIMARY KEY (id, created_at),
    CONSTRAINT fk_pv_test FOREIGN KEY (test_id)
        REFERENCES tests(id) ON DELETE SET NULL,
    CONSTRAINT fk_pv_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE SET NULL
) PARTITION BY RANGE (created_at);

CREATE INDEX page_views_created_idx
    ON page_views (created_at);
CREATE INDEX page_views_test_time_idx
    ON page_views (test_id, created_at) WHERE test_id IS NOT NULL;
CREATE INDEX page_views_path_idx
    ON page_views (path);

-- Example monthly partitions:
CREATE TABLE page_views_2026_06 PARTITION OF page_views
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE page_views_2026_07 PARTITION OF page_views
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE page_views_2026_08 PARTITION OF page_views
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

-- ============================================================================
-- 5. CHECK CONSTRAINTS
-- ============================================================================

-- offerings: price must be non-negative
ALTER TABLE offerings ADD CONSTRAINT offerings_price_nonneg
    CHECK (current_price IS NULL OR current_price >= 0);

-- price_history: new_price must be non-negative
ALTER TABLE price_history ADD CONSTRAINT price_history_new_price_nonneg
    CHECK (new_price >= 0);

-- proxies: counts must be non-negative
ALTER TABLE proxies ADD CONSTRAINT proxies_success_nonneg
    CHECK (success_count >= 0);
ALTER TABLE proxies ADD CONSTRAINT proxies_fail_nonneg
    CHECK (fail_count >= 0);

-- ============================================================================
-- 6. PARTIAL UNIQUE INDEXES (soft-delete safe)
-- ============================================================================

-- One active offering per test-vendor pair
CREATE UNIQUE INDEX offerings_test_vendor_active
    ON offerings (test_id, vendor_id)
    WHERE deleted_at IS NULL;

-- Vendor slugs unique among non-deleted vendors
CREATE UNIQUE INDEX vendors_slug_active
    ON vendors (slug)
    WHERE deleted_at IS NULL;

-- Test slugs unique among non-deleted tests
CREATE UNIQUE INDEX tests_slug_active
    ON tests (slug)
    WHERE deleted_at IS NULL;

-- ============================================================================
-- 7. PARTITION MAINTENANCE TEMPLATE
-- ============================================================================
-- The following is a template for the BullMQ partition-maintenance job.
-- It creates partitions 2 months ahead. Run monthly via scheduled job.
--
-- DO $$
-- DECLARE
--     target_month DATE;
--     partition_name TEXT;
--     start_date TEXT;
--     end_date TEXT;
--     tbl TEXT;
-- BEGIN
--     FOR i IN 1..2 LOOP
--         target_month := date_trunc('month', now()) + (i || ' months')::interval;
--         start_date := to_char(target_month, 'YYYY-MM-DD');
--         end_date := to_char(target_month + '1 month'::interval, 'YYYY-MM-DD');
--
--         FOREACH tbl IN ARRAY ARRAY['price_history', 'affiliate_clicks', 'search_logs', 'page_views'] LOOP
--             partition_name := tbl || '_' || to_char(target_month, 'YYYY_MM');
--             EXECUTE format(
--                 'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
--                 partition_name, tbl, start_date, end_date
--             );
--             RAISE NOTICE 'Created partition: %', partition_name;
--         END LOOP;
--     END LOOP;
-- END $$;
