-- LabPrice — PostgreSQL 16 DDL (Deliverable #2)
-- ----------------------------------------------------------------------------
-- Base CREATE TABLE statements for all 30 models are generated by `prisma migrate`
-- from schema.prisma. This file is the source of truth for the pieces Prisma
-- cannot model and that must be applied as manual migration steps:
--   • extensions
--   • CITEXT email column
--   • GENERATED tsvector + GIN full-text index
--   • RANGE partitioning of the high-volume time-series tables
--   • CHECK constraints and partial indexes
-- Representative full CREATEs are included for the 4 most important tables so the
-- intent is unambiguous; the rest follow the same conventions.
-- ----------------------------------------------------------------------------

-- 0. Extensions ---------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS citext;      -- case-insensitive email
CREATE EXTENSION IF NOT EXISTS pg_trgm;     -- fuzzy/typo-tolerant search
CREATE EXTENSION IF NOT EXISTS btree_gin;   -- composite GIN indexes
-- pg_partman optional for automated partition maintenance; cron job alternative documented.

-- 1. Catalog: tests (full example) -------------------------------------------
-- (enums created by Prisma; shown here for context)
-- CREATE TYPE "PublishStatus" AS ENUM ('DRAFT','PUBLISHED','ARCHIVED');

CREATE TABLE tests (
    id              TEXT PRIMARY KEY,
    category_id     TEXT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    name            TEXT NOT NULL,
    short_name      TEXT NOT NULL,
    slug            TEXT NOT NULL,
    status          "PublishStatus" NOT NULL DEFAULT 'DRAFT',
    is_popular      BOOLEAN NOT NULL DEFAULT FALSE,
    description     TEXT,
    purpose         TEXT,
    procedure       TEXT,
    preparation     TEXT,
    normal_range    TEXT,
    synonyms        TEXT[] NOT NULL DEFAULT '{}',
    seo_title       TEXT,
    seo_description TEXT,
    -- Full-text search vector, maintained automatically by Postgres:
    search_vector   tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(short_name, '')), 'A') ||
        setweight(to_tsvector('english', array_to_string(synonyms, ' ')), 'B')
    ) STORED,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL,
    deleted_at      TIMESTAMPTZ
);

CREATE UNIQUE INDEX tests_slug_key ON tests (slug);
CREATE INDEX tests_category_idx   ON tests (category_id);
CREATE INDEX tests_popular_idx    ON tests (is_popular) WHERE status = 'PUBLISHED' AND deleted_at IS NULL;
CREATE INDEX tests_search_gin     ON tests USING GIN (search_vector);
CREATE INDEX tests_synonyms_gin   ON tests USING GIN (synonyms);
CREATE INDEX tests_name_trgm      ON tests USING GIN (name gin_trgm_ops);   -- fuzzy autocomplete

-- 2. Offerings (full example) — the hot comparison table ----------------------
CREATE TABLE offerings (
    id                TEXT PRIMARY KEY,
    vendor_id         TEXT NOT NULL REFERENCES vendors(id) ON DELETE RESTRICT,
    test_id           TEXT NOT NULL REFERENCES tests(id)   ON DELETE RESTRICT,
    vendor_sku        TEXT,
    product_url       TEXT,
    current_price     NUMERIC(10,2),
    currency          CHAR(3) NOT NULL DEFAULT 'USD',
    includes_draw_fee BOOLEAN NOT NULL DEFAULT FALSE,
    in_stock          BOOLEAN NOT NULL DEFAULT TRUE,
    price_observed_at TIMESTAMPTZ,
    last_scraped_at   TIMESTAMPTZ,
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL,
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT offerings_vendor_test_key UNIQUE (vendor_id, test_id),
    CONSTRAINT offerings_price_nonneg CHECK (current_price IS NULL OR current_price >= 0)
);

-- The comparison query: WHERE test_id = ? AND is_active ORDER BY current_price
CREATE INDEX offerings_test_active_idx ON offerings (test_id)
    WHERE is_active = TRUE AND deleted_at IS NULL;
CREATE INDEX offerings_vendor_idx       ON offerings (vendor_id);
CREATE INDEX offerings_observed_idx     ON offerings (price_observed_at);

-- 3. price_history — append-only, RANGE partitioned by month ------------------
-- Note: a partitioned parent's PRIMARY KEY must include the partition key.
CREATE TABLE price_history (
    id            BIGSERIAL,
    offering_id   TEXT NOT NULL REFERENCES offerings(id) ON DELETE CASCADE,
    price         NUMERIC(10,2) NOT NULL,
    currency      CHAR(3) NOT NULL DEFAULT 'USD',
    in_stock      BOOLEAN NOT NULL,
    source        "PriceSource" NOT NULL,
    scrape_run_id TEXT REFERENCES scrape_runs(id),
    observed_at   TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, observed_at)
) PARTITION BY RANGE (observed_at);

CREATE INDEX price_history_offering_time_idx
    ON price_history (offering_id, observed_at DESC);

-- Example monthly partitions (created ahead of time by a maintenance job):
CREATE TABLE price_history_2026_06 PARTITION OF price_history
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE price_history_2026_07 PARTITION OF price_history
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
-- ... a cron/BullMQ job pre-creates next month's partition and detaches/archives
--     partitions older than the retention window (default 24 months).

-- 4. staged_price_changes — the approval queue (full example) -----------------
CREATE TABLE staged_price_changes (
    id               TEXT PRIMARY KEY,
    offering_id      TEXT NOT NULL REFERENCES offerings(id) ON DELETE CASCADE,
    scrape_result_id TEXT UNIQUE REFERENCES scrape_results(id),
    old_price        NUMERIC(10,2),
    new_price        NUMERIC(10,2) NOT NULL,
    delta_pct        NUMERIC(6,2),
    old_in_stock     BOOLEAN,
    new_in_stock     BOOLEAN,
    status           "ChangeStatus" NOT NULL DEFAULT 'PENDING',
    reason           TEXT,
    reviewed_by      TEXT REFERENCES users(id),
    reviewed_at      TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT staged_new_price_nonneg CHECK (new_price >= 0)
);
CREATE INDEX staged_status_idx   ON staged_price_changes (status, created_at);
CREATE INDEX staged_offering_idx ON staged_price_changes (offering_id);

-- 5. Other partitioned high-volume tables (same monthly pattern) --------------
-- affiliate_clicks, search_logs, page_views are PARTITION BY RANGE (created_at).
-- Each gets a per-month child + the indexes declared in schema.prisma.

-- 6. Constraints Prisma can't express ----------------------------------------
-- email is case-insensitive:
ALTER TABLE users ALTER COLUMN email TYPE CITEXT;

-- vendor rating bounded 1..5:
ALTER TABLE vendor_ratings ADD CONSTRAINT vendor_ratings_range CHECK (rating BETWEEN 1 AND 5);

-- a price alert watches exactly one of test OR offering:
ALTER TABLE price_alerts ADD CONSTRAINT price_alerts_target_xor
    CHECK ((test_id IS NOT NULL) <> (offering_id IS NOT NULL));

-- threshold required when kind = BELOW_THRESHOLD:
ALTER TABLE price_alerts ADD CONSTRAINT price_alerts_threshold_req
    CHECK (kind <> 'BELOW_THRESHOLD' OR threshold IS NOT NULL);

-- 7. Partial uniques for soft delete (slug reuse after archive is disallowed) --
-- tests.slug stays globally unique (immutable per BR-11); no partial needed.
